spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course

ali:
  oss:
    access-key-id: xx
    secret-access-key: xx
    endpoint: xx
    security-token: xx
    bucket: xx
    dir: xx