spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course

ali:
  oss:
    access-key-id: LTAI5t8wK7CC7mzRVx5qZaWb
    secret-access-key: vjnYrX564nKkm04mUWa6kdDnpQY26a
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucket: wszzf
    dir: course
